# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mousehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='album_link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
