# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mousehouse', '0002_auto_20180607_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='album_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
