# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mousehouse', '0005_auto_20180608_0015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': (('view_pg', 'Can see PG Posts'), ('view_adult', 'Can see Adult Posts'), ('view_adult_plus', 'Can see Adult Plus Posts'))},
        ),
    ]
